version: "3.8"

services:
  # IRC server: InspIRCd
  ircd:
    image: inspircd/inspircd-docker:latest
    # Expose the standard IRC port
    ports:
      - "6667:6667"
    # Basic environment customization (network name, admin email, etc.)
    environment:
      - INSP_NET_NAME=porant
      - INSP_ADMIN_NAME=ServerAdmin
      - INSP_ADMIN_EMAIL=admin@irc.example.com
      - INSP_ENABLE_DNSBL=no
    # Persist generated configs across deployments
    volumes:
      - ircd-data:/inspircd/conf
    networks:
      - dokploy-network

  # Web-based IRC client: Kiwi IRC
  kiwiirc:
    image: itzg/kiwi-irc:latest           # official Kiwi IRC image
    
    ports:
      - "7778:7778"                       # publish Kiwi’s web UI port
    volumes:
      - ./config.json:/opt/KiwiIRC/static/config.json:ro  # mount your config
    environment:
      - WEBIRCGATEWAY_CONFIG=/opt/KiwiIRC/static/config.json
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.kiwiirc.rule=Host(`chat.porant.de`)"
      - "traefik.http.routers.kiwiirc.entrypoints=websecure"
      - "traefik.http.routers.kiwiirc.tls.certresolver=letsencrypt"
      - "traefik.http.services.kiwiirc.loadbalancer.server.port=7778"
    networks:
      - dokploy-network

networks:
  # Dokploy will auto-create and attach this external network
  dokploy-network:
    external: true

volumes:
  ircd-data:
