version: "3.8"

services:
  # IRC server: InspIRCd
  ircd:
    image: inspircd/inspircd-docker:latest
    # Expose the standard IRC port
    ports:
      - "6667:6667"
    # Basic environment customization (network name, admin email, etc.)
    environment:
      - INSP_NET_NAME=porant
      - INSP_ADMIN_NAME=ServerAdmin
      - INSP_ADMIN_EMAIL=admin@irc.example.com
      - INSP_ENABLE_DNSBL=no
    # Persist generated configs across deployments
    volumes:
      - ircd-data:/inspircd/conf
    networks:
      - dokploy-network

networks:
  # Dokploy will auto-create and attach this external network
  dokploy-network:
    external: true

volumes:
  ircd-data: