version: '3.8' # Or remove this line

services:
  inspircd:
    image: inspircd/inspircd-docker:latest # Or pinned version
    container_name: inspircd-server
    restart: unless-stopped
    ports:
      - "6667:6667"
      - "6697:6697"
    volumes:
      - ./conf:/inspircd/conf
      - inspircd-logs:/inspircd/logs
      - extracted-certs:/etc/ssl/ircd:ro # Mount point for extracted certs
    depends_on:
      - cert-dumper # Wait for dumper to start

  cert-dumper: # *** SERVICE USING LOCAL BUILD ***
    build:
      context: ./conf # Build context is the conf directory
      dockerfile: Dockerfile.dumper # Specify our Dockerfile name
    container_name: local-cert-dumper-irc
    restart: unless-stopped
    volumes:
      # Mount acme.json from host READ-ONLY
      - /etc/dokploy/traefik/dynamic/acme.json:/input/acme.json:ro
      # Mount the volume where PEM files will be written
      - extracted-certs:/output

volumes:
  inspircd-logs:
  extracted-certs: