version: '3.8'

services:
  inspircd:
    image: inspircd/inspircd-docker:latest # Or pinned version
    container_name: inspircd-server
    restart: unless-stopped
    ports:
      - "6667:6667"
      - "6697:6697"
    volumes:
      # Existing config mount
      - ./conf:/inspircd/conf
      # Existing logs mount
      - inspircd-logs:/inspircd/logs
      # *** NEW: Mount the extracted certs (read-only) ***
      - extracted-certs:/etc/ssl/ircd:ro
    depends_on: # Optional but good practice: wait for dumper to potentially run once
      - cert-dumper

  cert-dumper: # *** NEW SERVICE ***
    image: ldez/traefik-cert-dumper:latest
    container_name: traefik-cert-dumper-irc # Specific name
    restart: unless-stopped
    volumes:
      # Mount acme.json from host (path confirmed) READ-ONLY
      - /etc/dokploy/traefik/dynamic/acme.json:/input/acme.json:ro # Mount to /input/acme.json
      # Mount the volume where PEM files will be written
      - extracted-certs:/output
    # command: # Optional: Increase wait time if needed
    #   - dump
    #   - --watch
    #   - --source /input/acme.json
    #   - --dest /output
    #   - --domain irc.porant.de # Only dump this domain if acme.json has others
    #   - --wait 300 # Wait 5 minutes between checks

volumes:
  inspircd-logs:
  extracted-certs: # *** NEW NAMED VOLUME ***