version: "3.8"

services:
  # IRC server: InspIRCd
  ircd:
    image: inspircd/inspircd-docker:latest
    # Expose the standard IRC port
    ports:
      - "6667:6667"
    # Basic environment customization (network name, admin email, etc.)
    environment:
      - INSP_NET_NAME=porant
      - INSP_ADMIN_NAME=ServerAdmin
      - INSP_ADMIN_EMAIL=admin@irc.example.com
      - INSP_ENABLE_DNSBL=no
    # Persist generated configs across deployments
    volumes:
      - ircd-data:/inspircd/conf
    networks:
      - dokploy-network

  # Web-based IRC client: Kiwi IRC
  kiwiirc:
    image: itzg/kiwi-irc:latest
    ports:
      - "7778:7778"
    volumes:
      - ./config.js:/opt/KiwiIRC/config.js:ro
    command: >
      sh -c "rm -rf /opt/KiwiIRC/static/dist && kiwiirc"
    environment:
      - WEBIRCGATEWAY_CONFIG=/opt/KiwiIRC/config.js
    labels:
      # Enable Traefik for this service
      - "traefik.enable=true"  
      # Route HTTPS requests for chat.porant.de to this container
      - "traefik.http.routers.kiwi.rule=Host(`chat.porant.de`)"  
      # Use the websecure entrypoint (TLS) defined in your Traefik
      - "traefik.http.routers.kiwi.entrypoints=websecure"  
      # Obtain/renew certificates via Let's Encrypt
      - "traefik.http.routers.kiwi.tls.certresolver=letsencrypt"  
      # Tell Traefik the container’s internal port to forward to
      - "traefik.http.services.kiwi.loadbalancer.server.port=7778"  
      # (Optional) Redirect HTTP → HTTPS
      - "traefik.http.routers.kiwi-http.rule=Host(`chat.porant.de`)"  
      - "traefik.http.routers.kiwi-http.entrypoints=web"  
      - "traefik.http.routers.kiwi-http.middlewares=redirect-to-https@docker"  
  networks:
    - dokploy-network

volumes:
  ircd-data:
